apiVersion: v1
kind: Service
metadata:
  name: counter-service
  namespace: tomer-candidate
spec:
  type: LoadBalancer
  selector:
    app: counter-service
  ports:
  - name: http
    port: 80
    targetPort: 80
